version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Build started on $(date)
      - python hello_world.py
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  files:
    - hello_world.py

